# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:

      - checkout

      - run:
          name: Install MySQL client
          command: |
            sudo apt-get update
            # sudo apt-get install -y libzip-dev
            # sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo apt-get install -y mysql-client
            mysql --version

      - setup_remote_docker:
          # version: 17.05.0-ce
          docker_layer_caching: true
      - run: docker version
      - run: docker-compose version
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
          environment:
            DOCKER_COMPOSE_VERSION: 1.22.0

      - run: docker version
      - run: docker-compose version
      - run:
          name: Eexecute docker-compose
          command: |
            docker-compose up  --build --detach

      # - run: ruby -v
      # - run: mysql --host 127.0.0.1 --port 3306 -uroot -e 'status;'

